graph LR
    A[UV Numérique]
    A --> B1[Parcours SISC<br /> > Res. Télécom] --> C11[...]
    A --> B2[Parcours RAISE <br /> > Data] --> C21[Spé. 1 <br /> > Image Multimedia]
    A --> B3[Parcours ID<br /> > Indus. Durable] --> C31[...]
    B2 --> C22[Spé. 2 <br /> > LoDSC]