gantt
    title UV de la Spé. LoDSC
    dateFormat YYYY-MM-DD
    section UV LoDI
        Semestre 1 - 96h :spe1, 1000-08-01,1000-11-01
    section UV MAPS
        Semestre 1 - 96h :1000-09-01,1000-12-15
    section UV TIJS
        Semestre 1/2 - 96h :1000-11-01,1001-03-01
    section PFE
        Semestre 1/2 - 96h :1001-03-01,1001-07-01